Review Changes
adobe/plugin-hooks pull request #1
Opened 2023-08-25 14:33 UTC by AjazSumaiya

## Description
This is a review branch for making the package public.

After review completes, this will be merged to main and a commit release will be pushed to the main branch that will 
publish the package.

## PR Related Changes
Changes done as part of this PR. 

-  removed the npmrc file from this public repo since it is not required anymore as we are publishing to open npm registry neither we will be using the package that is on artifactory as that has to be deprecated after this package gets released.
- updated package.json file to include the open github repo link, publish configs and version as 0.1.0.
- updated publish-npm.yml file taking in reference from the guild open-source formatter repo https://github.com/adobe/starter-repo/blob/master/.github/workflows/npm-publish.yml 
    > review the file https://github.com/adobe/plugin-hooks/blob/review/repo/.github/workflows/publish-to-npm.yml of this repo, if any changes need to be made.

- formatted repo referencing the open source template starter repo https://github.com/adobe/starter-repo

    > As part of formatting all these files were added License file in the root of the repo
    > - License headers in all code files
    > - Approved code of conduct
    > - Contribution guidelines

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-25 15:23 UTC, dthampy approved these changes

2023-08-25 19:46 UTC, brasewel requested changes

2023-08-25 19:46 UTC, brasewel commented on .github/workflows/publish-to-npm.yml
> +          NPM_AUTH: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
I don't think these are required. If you look at how Deepty did it in the cli repo, you just need the adobe npm token. Please remove these and look at the cli for reference

2023-08-28 07:40 UTC, AjazSumaiya commented on .github/workflows/publish-to-npm.yml
> +          commit_pattern: "^Release (\\S+)"
Hi @amolina-adobe, yeah, the commit pattern you suggested seems better than this "^Release (\\S+)" as this is more restrictive match. 

This pattern i took from the starter repo template only https://github.com/adobe/starter-repo/blob/master/.github/workflows/npm-publish.yml. 

But you seem right it should match all the non-whitespace characters after the space.

2023-08-28 07:59 UTC, AjazSumaiya commented on .github/workflows/publish-to-npm.yml
> +          NPM_AUTH: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
yeah @amolina-adobe and @brasewel  i was not sure on this as the template seems to be updated from the one, we used in cli repo.

I replicated the template as is here.

But we are not using NPM_AUTH anywhere so we can remove it. maybe this naming is more conventional for .npmrc file that we are not using.

2023-08-29 15:07 UTC, brasewel approved these changes

2023-08-29 15:09 UTC, brasewel requested changes

2023-08-29 15:09 UTC, brasewel commented on .github/workflows/publish-to-npm.yml
> -  push:
You will also want to follow how we do this in the cli where we only publish on the main branch

2023-08-29 15:11 UTC, brasewel requested changes
This change also needs to go into develop first

2023-08-29 16:00 UTC, amolina-adobe requested changes

2023-08-31 12:25 UTC, AjazSumaiya commented on .github/workflows/publish-to-npm.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
removed the token as it is not required

2023-09-05 19:13 UTC, amolina-adobe approved these changes

2023-09-06 14:20 UTC, brasewel approved these changes

2023-09-06 14:39 UTC, merged